#!/bin/bash
# Copyright 2026 Chris Farris <chris@primeharbor.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generate Granted/AWS CLI config file from Terraform output JSON
#
# Usage: ./scripts/generate_granted_config.sh <output-file.json>
#
# Arguments:
#   output-file.json - Path to the Terraform output JSON file (e.g., output-pht.json)
#
# Example:
#   ./scripts/generate_granted_config.sh output-pht.json > ~/.aws/config

set -e

# Check for required argument
if [ $# -ne 1 ]; then
    echo "Error: Missing required argument" >&2
    echo "Usage: $0 <output-file.json>" >&2
    exit 1
fi

OUTPUT_JSON="$1"

# Check if the input file exists
if [ ! -f "$OUTPUT_JSON" ]; then
    echo "Error: File not found: $OUTPUT_JSON" >&2
    exit 1
fi

# Read the JSON file
OUTPUTS=$(cat "$OUTPUT_JSON")

# Extract values from outputs
ACCOUNT_MAP=$(echo "$OUTPUTS" | jq -r '.account_map.value // empty')
SSO_START_URL=$(echo "$OUTPUTS" | jq -r '.sso_start_url.value // empty')
SSO_REGION=$(echo "$OUTPUTS" | jq -r '.sso_region.value // empty')
SSO_ROLE_NAME=$(echo "$OUTPUTS" | jq -r '.sso_role_name.value // empty')
ORG_NAME=$(echo "$OUTPUTS" | jq -r '.org_name.value // empty')

# Validate required outputs
if [ -z "$ACCOUNT_MAP" ] || [ "$ACCOUNT_MAP" = "null" ]; then
    echo "Error: account_map not found in JSON" >&2
    exit 1
fi

if [ -z "$SSO_START_URL" ] || [ "$SSO_START_URL" = "null" ]; then
    echo "Error: sso_start_url not found in JSON" >&2
    exit 1
fi

if [ -z "$SSO_REGION" ] || [ "$SSO_REGION" = "null" ]; then
    echo "Error: sso_region not found in JSON" >&2
    exit 1
fi

if [ -z "$SSO_ROLE_NAME" ] || [ "$SSO_ROLE_NAME" = "null" ]; then
    echo "Error: sso_role_name not found in JSON" >&2
    exit 1
fi

if [ -z "$ORG_NAME" ] || [ "$ORG_NAME" = "null" ]; then
    echo "Error: org_name not found in JSON" >&2
    exit 1
fi

# Set SSO session name
SSO_SESSION_NAME="${ORG_NAME}-sso"

# Start writing the config to stdout
cat << EOF
##############################################################################
#
# AWS Organization Accounts - ${ORG_NAME} 
# Generated by org-kickstart: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
#

[sso-session $SSO_SESSION_NAME]
sso_start_url = $SSO_START_URL
sso_region = $SSO_REGION
sso_registration_scopes = sso:account:access


EOF

# Parse account map and generate profiles
echo "$ACCOUNT_MAP" | jq -r 'to_entries | sort_by(.key) | .[] | @json' | while read -r account; do
    ACCOUNT_NAME=$(echo "$account" | jq -r '.key')
    ACCOUNT_ID=$(echo "$account" | jq -r '.value')

    cat << EOF
[profile $ACCOUNT_NAME]
sso_session    = $SSO_SESSION_NAME
sso_account_id = $ACCOUNT_ID
sso_role_name  = $SSO_ROLE_NAME

EOF
done
